name = "Graphs"
uuid = "86223c79-3864-5bf0-83f7-82e725a168b6"
keywords = ["Graphs"]
desc = "Traditional graphing library for a variety of graph types."
version = "0.10.3"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DataStructures = "â‰¥ 0.14"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
